version: '3.8'
# 命令执行 docker-compose -f docker-compose-app.yml up -d
services:
  big-market-app-01:
    image: system/big-market-app:4.1
    container_name: big-market-app-01
    restart: always
    ports:
      - "9081:9081"
    environment:
      - TZ=PRC
      - SERVER_PORT=9081
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
    volumes:
      - ./log:/data/log
    networks:
      - my-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 访问地址 http://116.198.36.253/?userId=xiaofuge&activityId=100301
  big-market-front-app:
    container_name: big-market-front-app
    image: system/big-market-front-app:4.1
    restart: always
    networks:
      - my-network
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://0.0.0.0:3000/" ]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge